### ISSUE TITLE
Code Robustness

### ISSUE THREAD

**Issue by haskarb** [dockleryxk/PSO#1]
Did you check your code against the 28 benchmark test functions described here. Specially, Shekel's function.
[www.nnw.cz/doi/2013/NNW.2013.23.013.pdf](url)

**Comment by dockleryxk** [comment]
@dhariyalbhaskar I wrote this years ago, and have not written much Python since. I was still in school when I wrote this. Now, I am a completely different person (and developer!).

Anyways, thank you for this suggestion. I need a good Python refresher, and this is a great way for me to do that! I appreciate the suggestion and will definitely read through this
